# Generated by Django 3.2.4 on 2021-06-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='descripton',
            field=models.TextField(max_length=1000),
        ),
    ]
