# Generated by Django 3.1.7 on 2021-06-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('postedby', models.CharField(max_length=50)),
                ('userenroll', models.CharField(max_length=50)),
                ('useremail', models.CharField(max_length=80)),
                ('issuecat', models.CharField(max_length=20)),
                ('issuedesc', models.TextField()),
            ],
        ),
    ]
