# Generated by Django 3.1.7 on 2021-06-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=100)),
                ('postedby', models.CharField(max_length=50)),
                ('userenroll', models.CharField(max_length=50)),
                ('useremail', models.CharField(max_length=80)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
