# Generated by Django 3.2.4 on 2021-06-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
