# Generated by Django 2.2.1 on 2021-06-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210614_2139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
