# Generated by Django 3.1.7 on 2021-06-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_extuser_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='extuser',
            name='cemail',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
