# Generated by Django 3.1.7 on 2021-06-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_extuser_cemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='sem',
            field=models.CharField(blank=True, default='First', max_length=50),
        ),
    ]
