# Generated by Django 2.2.24 on 2021-06-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210614_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='extuser',
            name='profileimg',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
