# Generated by Django 2.2.24 on 2021-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210616_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='extuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('HOD', 'Head of Department'), ('Faculty', 'Faculty'), ('SS', 'Students Department'), ('AS', 'Accounts Department')], default='Student', max_length=100),
        ),
    ]
