# Generated by Django 2.2.24 on 2021-06-18 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_extuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
