# Generated by Django 2.2.24 on 2021-06-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210618_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='profileimg',
            field=models.ImageField(default='profile_images/user.png', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='extuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('HOD', 'Head of Department'), ('Faculty', 'Faculty'), ('Students Dept.', 'Students Department'), ('Accounts Dept.', 'Accounts Department'), ('D.G.', 'Director General'), ('Principal', 'Principal'), ('Moderator', 'Moderator')], default='Student', max_length=100),
        ),
    ]
