# Generated by Django 2.2.24 on 2021-06-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210618_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='department',
            field=models.CharField(blank=True, default='IIST', max_length=100),
        ),
    ]
