# Generated by Django 2.2.24 on 2021-06-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
