# Generated by Django 2.2.24 on 2021-06-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comshop', '0002_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='postedby',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
