# Generated by Django 2.2.24 on 2021-06-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comshop', '0003_auto_20210615_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='postdate',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
