# Generated by Django 2.2.1 on 2021-06-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('descripton', models.TextField(max_length=1000)),
                ('file', models.FileField(upload_to='notice/')),
            ],
        ),
    ]
