# Generated by Django 2.2.24 on 2021-06-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210618_1149'),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.extUser'),
        ),
        migrations.AddField(
            model_name='notice',
            name='slug',
            field=models.SlugField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
